### ISSUE TITLE
Angular-material import error

### ISSUE THREAD

**Issue by rememberlenny** [titonobre/storybook-addon-angularjs-example#1]
Thanks for making this!

I'm struggling to get `angular-material` to import and properly run in this environment.

When I add `ngMaterial, ngAnimate, ngAria` and the respective imports to the parent level app module, I get the following error:

```
[$injector:unpr] Unknown provider: $rootElementProvider <- $rootElement <- $$animateQueue <- $animate <- $compile <- $mdUtil <- $mdTheming <- $$animateQueue https://errors.angularjs.org/1.7.5/$injector/unpr?p0=%24rootElementProvider%20%3C-%20%24rootElement%20%3C-%20%24%24animateQueue%20%3C-%20%24animate%20%3C-%20%24compile%20%3C-%20%24mdUtil%20%3C-%20%24mdTheming%20%3C-%20%24%24animateQueue
```

Do you have any thoughts on what might be happening on the storybook end that causes this? From the error, I understand that there may be some unintended imports inside imports, but I can't seem to figure it out.

**Comment by titonobre** [comment]
Hi @rememberlenny.

In fact this was reported earlier here: https://github.com/titonobre/storybook-addon-angularjs/pull/1.
The reason for not having merged the PR is that I think this this can be handled outside the addon.

I've made a small example here: https://github.com/titonobre/storybook-addon-angularjs-example/commit/513f0b755ea5383222b0f4493eafd5f0cc1616f3 with angular-material.

Let me know if this fits your needs.
