### ISSUE TITLE
Resolving module dependencies

### ISSUE THREAD

**Issue by pmachaux** [titonobre/storybook-addon-angularjs-example#2]
Hi,

First thank you for your work. It's very appreciated that you what you did.
I have question for you. I downloaded your example and it work out of the box.
When I try to add a dependency to the MyAppModule I get the following error

![image](https://user-images.githubusercontent.com/21976890/55988763-b8533a00-5c72-11e9-967b-c770d952cb39.png)

It seems that we cannot resolve any dependency. Do you know a way of doing that ?
What I would like to achieve is to resolve modules that look like this:

![image](https://user-images.githubusercontent.com/21976890/55988827-e3d62480-5c72-11e9-92b6-2808f2059a98.png)

Ideally in Storybook, we could provide mock dependencies for this module to enable its resolution.

Do you have some ideas about this ?

**Comment by pmachaux** [comment]
Never mind I finally found how to do it.
In bootstrap.js I import the module and it works.
Funny thing removing the angular.bootstrap line does not break anything. We just need the imports

I close the ticket. Thank you for your awesome addon !

**Comment by titonobre** [comment]
So sorry for the late reply. I've been busy for the last few days.

I'm happy to know that you overcome the difficulties.

The bootstrap was indeed part of an initial experiment. I hope to have some free time improve this example with different usages with and without explicit bootstrap.

**Comment by pmachaux** [comment]
No worries, this is the same for me !
In any case, this is great work. Simple and efficient ! Thanks again
