### ISSUE TITLE
Services and injections question

### ISSUE THREAD

**Issue by couchemar** [titonobre/storybook-addon-angularjs-example#5]
I have some services injected in my component, how can I mock or initialize this services in storybook?

**Comment by diondree** [comment]
I'm also experiencing issues attempting to do this. Have you found a solution as yet? @couchemar

**Comment by titonobre** [comment]
Hi.
I the next few days I will try to find a way to do this.

**Comment by diondree** [comment]
Hi, that would be awesome. Please let me know if there's any way I can help.

**Comment by couchemar** [comment]
Hi!

> I'm also experiencing issues attempting to do this. Have you found a solution as yet? @couchemar

@diondree, i still have no good solution

 > Hi.
I the next few days I will try to find a way to do this.

@titonobre, that would be great!

**Comment by couchemar** [comment]
Today I have had eureka moment. And I discovered quite simple solution. Not very elegant, but just covers my needs.

We can define simple component for app:

```
angular.module('myApp').component(
        'withInjector',
        {
            bindings: {
                do: '='
         },
         transclude: true,
         controller: function($injector) {
              this.$onInit = () => {
                  if (this.do !== undefined) {
                      this.do($injector);
                  }
              };
          },
          template: '<div ng-transclude></div>'
      }
);

angular.bootstrap(document.body, ['myApp']);
```

And we can use this component in our stories this way:
```
           ...
           function init ($injector) {
                 $injector.invoke(['serviceA', 'serviceB', (a, b) => {
                     // do something with a and b
                     a.foo();
                     b.bar();
                }]);
            };

            return compile`
<with-injector do="${init}">
  <my-shiny-component></my-shiny-component>
<with-injector>
`;
```
However, I did not check for more complex cases.
